# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 637)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableUser1toUser2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableUser1toUser2.setGeometry(QtCore.QRect(40, 70, 311, 371))
        self.tableUser1toUser2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableUser1toUser2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableUser1toUser2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableUser1toUser2.setObjectName("tableUser1toUser2")
        self.tableUser1toUser2.setColumnCount(4)
        self.tableUser1toUser2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("ID")
        self.tableUser1toUser2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser1toUser2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser1toUser2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser1toUser2.setHorizontalHeaderItem(3, item)
        self.labelUser1_1 = QtWidgets.QLabel(self.centralwidget)
        self.labelUser1_1.setGeometry(QtCore.QRect(70, 40, 47, 13))
        self.labelUser1_1.setObjectName("labelUser1_1")
        self.btnChangeUser1Name = QtWidgets.QPushButton(self.centralwidget)
        self.btnChangeUser1Name.setGeometry(QtCore.QRect(380, 70, 121, 23))
        self.btnChangeUser1Name.setObjectName("btnChangeUser1Name")
        self.labelUser2_1 = QtWidgets.QLabel(self.centralwidget)
        self.labelUser2_1.setGeometry(QtCore.QRect(180, 40, 47, 13))
        self.labelUser2_1.setObjectName("labelUser2_1")
        self.labelTo1 = QtWidgets.QLabel(self.centralwidget)
        self.labelTo1.setGeometry(QtCore.QRect(120, 40, 47, 13))
        self.labelTo1.setObjectName("labelTo1")
        self.btnChangeUser2Name = QtWidgets.QPushButton(self.centralwidget)
        self.btnChangeUser2Name.setGeometry(QtCore.QRect(380, 120, 121, 23))
        self.btnChangeUser2Name.setObjectName("btnChangeUser2Name")
        self.labelTotalUser1 = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalUser1.setGeometry(QtCore.QRect(50, 500, 111, 16))
        self.labelTotalUser1.setObjectName("labelTotalUser1")
        self.labelNetDebt = QtWidgets.QLabel(self.centralwidget)
        self.labelNetDebt.setGeometry(QtCore.QRect(420, 190, 47, 13))
        self.labelNetDebt.setObjectName("labelNetDebt")
        self.btnAddEntryUser1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddEntryUser1.setGeometry(QtCore.QRect(40, 450, 75, 23))
        self.btnAddEntryUser1.setAutoDefault(True)
        self.btnAddEntryUser1.setObjectName("btnAddEntryUser1")
        self.btnDeleteEntryUser1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeleteEntryUser1.setGeometry(QtCore.QRect(130, 450, 75, 23))
        self.btnDeleteEntryUser1.setAutoDefault(False)
        self.btnDeleteEntryUser1.setObjectName("btnDeleteEntryUser1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableUser1toUser2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableUser1toUser2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Debt"))
        item = self.tableUser1toUser2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date"))
        self.labelUser1_1.setText(_translate("MainWindow", "User1"))
        self.btnChangeUser1Name.setText(_translate("MainWindow", "Change User1 name"))
        self.labelUser2_1.setText(_translate("MainWindow", "User2"))
        self.labelTo1.setText(_translate("MainWindow", "to"))
        self.btnChangeUser2Name.setText(_translate("MainWindow", "Change User2 name"))
        self.labelTotalUser1.setText(_translate("MainWindow", "Total:"))
        self.labelNetDebt.setText(_translate("MainWindow", "Net Debt"))
        self.btnAddEntryUser1.setText(_translate("MainWindow", "Add entry"))
        self.btnDeleteEntryUser1.setText(_translate("MainWindow", "Delete entry"))
